const companyToken = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6OTgsImVtYWlsIjoiZnJhbmNlc2NvLnNnaGVyemkuZGV2QGdtYWlsLmNvbSIsImJlZ2luX3RpbWUiOiIyMDE5LTAxLTA3VDE2OjA0OjU5Ljk0MloiLCJpYXQiOjE1NDY4NzcwOTksImV4cCI6MTU0Njk2MzQ5OX0.dCSpwwpV8OkKVXTxc1oC7nvu817mIPkOoIqQt7RQBdQ'
const userToken = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NjIsImVtYWlsIjoiZnJhbmNlc2NvLnNnaGVyemlAZ21haWwuY29tIiwiYmVnaW5fdGltZSI6IjIwMTgtMTItMjhUMjM6MTE6NDIuMTk2WiIsImlhdCI6MTU0NjAzODcwMiwiZXhwIjoxNTQ2MTI1MTAyfQ.1EUgQimBcVagi7LlnDRMFTU4jOvAfiXEDE3x5MGpJxE'
const runOrganizerToken = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NjQsImVtYWlsIjoiZnJhbmNlc2NvLnNnaGVyemlAdG9ycmVzY2FsbGEuaXQiLCJiZWdpbl90aW1lIjoiMjAxOC0xMi0zMFQxODoxNjo0Ny44NTBaIiwiaWF0IjoxNTQ2MTkzODA3LCJleHAiOjE1NDYyODAyMDd9.TILAsVZAlfa2ihRlH-s0f6bstYGxPjwYQPWuiA5ifRw'
const LOCAL_BASE_URL = 'http://localhost:12345/'
const HEROKU_BASE_URL = 'https://data4halp.herokuapp.com/'


module.exports = {
  userToken,
  companyToken,
  runOrganizerToken,
  LOCAL_BASE_URL,
  HEROKU_BASE_URL
}